[tool.poetry]
name = "bleak_house"
version = "0.1.0"
description = ""
authors = ["Chris Brew <brewc@dy6nm2ng4q.legal.regn.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
sf-hamilton = {extras = ["visualization"], version = "^1.85.0"}
loguru = "^0.7.3"
burr = {extras = ["graphviz", "hamilton", "streamlit", "tracking-client", "tracking-server"], version = "^0.34.1"}
jupter = "^0.1.0"
lab = "^8.3"
notebook = "^7.3.1"
anthropic = "^0.40.0"
lxml = "^5.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
