[tool.poetry]
name = "bleak_house"
version = "0.1.0"
description = ""
authors = ["Chris Brew <brewc@dy6nm2ng4q.legal.regn.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
sf-hamilton = {extras = ["visualization"], version = "^1.85.1"}
loguru = "^0.7.3"
burr = {extras = ["opentelemetry", "start"], version = "^0.35.1"}
jupter = "^0.1.0"
lab = "^8.3"
notebook = "^7.3.2"
anthropic = "^0.40.0"
lxml = "^5.3.0"
openai = "^1.58.1"
lancedb = "^0.17.0"
pydantic = "^2.10.4"
pyarrow = "^18.1.0"
opentelemetry-instrumentation-openai = "^0.34.0"
opentelemetry-instrumentation-lancedb = "^0.34.0"
sentence-transformers = "^3.3.1"
scikit-learn = "^1.6.0"
tqdm = "^4.67.1"
scipy = "^1.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
