"""Generate provenance data for poster_print.html and write poster_provenance.js.

Also updates webapp/static/provenance.json with a 'poster' entry so the
site-standard provenance badge appears when the poster is viewed in the webapp.
"""
import json
import re
import subprocess
from pathlib import Path

POSTER_PATH = "poster/poster_print.html"
OUT_PATH = Path(__file__).parent / "poster_provenance.js"
PROVENANCE_JSON = Path(__file__).parent.parent / "webapp" / "static" / "provenance.json"
GITHUB_URL = "https://github.com/cbrew/BleakHouse/commits/main/poster/poster_print.html"

HUMAN_SIGNAL_RE = re.compile(
    r"\b("
    r"user[- ]edit(?:s|ed)?|"
    r"per user edit(?:s)?|"
    r"user[- ]directed|"
    r"user requested|"
    r"human[- ]edit(?:ed)?|"
    r"human written|"
    r"effectively human"
    r")\b",
    re.IGNORECASE,
)


def run_git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout


def load_commits(path: str) -> list[dict]:
    raw = run_git("log", "--format=%H%x1f%s%x1f%b%x1e", "--", path)
    commits = []
    for record in raw.split("\x1e"):
        if not record.strip():
            continue
        parts = record.strip().split("\x1f")
        if len(parts) != 3:
            continue
        commit_hash, subject, body = parts
        message = f"{subject}\n{body}".strip()
        commits.append(
            {
                "hash": commit_hash,
                "message": message,
                "has_human_signal": bool(HUMAN_SIGNAL_RE.search(message)),
            }
        )
    return commits


def blame_line_counts(path: str) -> dict[str, int]:
    raw = run_git("blame", "--line-porcelain", path)
    counts: dict[str, int] = {}
    for line in raw.splitlines():
        if re.match(r"^[0-9a-f]{40} \d+ \d+( \d+)?$", line):
            parts = line.split()
            h = parts[0]
            n = int(parts[3]) if len(parts) > 3 else 1
            counts[h] = counts.get(h, 0) + n
    return counts


def classify(path: str) -> dict:
    commits = load_commits(path)
    total = len(commits)
    blame_counts = blame_line_counts(path) if total else {}
    total_lines = sum(blame_counts.values())

    ai_count = 0
    for commit in commits:
        body = run_git("log", "-1", "--format=%b", commit["hash"])
        if "Co-Authored-By" in body and "Claude" in body:
            ai_count += 1

    human_edit_commits = [c for c in commits if c["has_human_signal"]]
    human_edit_hashes = {c["hash"] for c in human_edit_commits}
    human_edit_lines = sum(blame_counts.get(h, 0) for h in human_edit_hashes)
    human_edit_ratio = (human_edit_lines / total_lines) if total_lines else 0.0
    latest_is_human = bool(commits and commits[0]["hash"] in human_edit_hashes)
    effectively_human = (
        total >= 2
        and human_edit_lines >= 20
        and human_edit_ratio >= 0.6
        and (latest_is_human or len(human_edit_commits) >= 2)
    )

    if total == 0:
        badge, color = "unknown", "grey"
    elif effectively_human:
        badge, color = "Effectively human-written", "green"
    elif bool(human_edit_commits) and total >= 2:
        badge, color = "AI-drafted, human-edited", "yellow"
    else:
        badge, color = "AI-drafted", "red"

    return {
        "badge": badge,
        "color": color,
        "totalCommits": total,
        "aiCommits": ai_count,
        "humanEditCommits": len(human_edit_commits),
        "humanEditRatio": round(human_edit_ratio, 3),
    }


data = classify(POSTER_PATH)
js = f"/* Auto-generated by gen_poster_provenance.py — do not edit */\nwindow.POSTER_PROVENANCE = {json.dumps(data, indent=2)};\n"
OUT_PATH.write_text(js)
print(f"Written {OUT_PATH}")
print(json.dumps(data, indent=2))

# Also update provenance.json so the site-standard badge works on /poster
if PROVENANCE_JSON.exists():
    prov = json.loads(PROVENANCE_JSON.read_text())
else:
    prov = {}

prov["poster"] = {
    "badge": data["badge"],
    "color": data["color"],
    "total_commits": data["totalCommits"],
    "ai_commits": data["aiCommits"],
    "human_edits": data["humanEditCommits"],
    "human_edit_lines": 0,
    "human_edit_ratio": data["humanEditRatio"],
    "github_url": GITHUB_URL,
}
PROVENANCE_JSON.write_text(json.dumps(prov, indent=4) + "\n")
print(f"Updated {PROVENANCE_JSON} with poster entry")
