/* Auto-generated by gen_poster_provenance.py — do not edit */
window.POSTER_PROVENANCE = {
  "badge": "AI-drafted",
  "color": "red",
  "totalCommits": 9,
  "aiCommits": 9,
  "humanEditCommits": 0,
  "humanEditRatio": 0.0
};
