"""Generate provenance badges for webapp pages based on git history."""
import json
import os
import re
import subprocess

PAGES_DIR = "webapp/pages"
GITHUB_BASE = "https://github.com/cbrew/BleakHouse"

HUMAN_SIGNAL_RE = re.compile(
    r"\b("
    r"user[- ]edit(?:s|ed)?|"
    r"per user edit(?:s)?|"
    r"user[- ]directed|"
    r"user requested|"
    r"human[- ]edit(?:ed)?|"
    r"human written|"
    r"effectively human"
    r")\b",
    re.IGNORECASE,
)

AI_GENERATED_RE = re.compile(r"AI-generated by Claude Code", re.IGNORECASE)

# Pages to badge (exclude podcast scripts/reports — those are fully AI)
PAGES = {}
for f in sorted(os.listdir(PAGES_DIR)):
    if f.endswith(".html"):
        PAGES[f.replace(".html", "")] = os.path.join(PAGES_DIR, f)

# Pages where user provided significant editorial direction
HUMAN_DIRECTED = {
    "landing",  # user directed structure, motivation, professional framing
    "blog",     # user renamed sections, directed content additions
    "research", # user directed honest qualification of claims
    "help",     # user requested references move, In Our Time fix
}


def run_git(*args: str) -> str:
    return subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def load_commits(path: str) -> list[dict[str, str | bool]]:
    raw = run_git("log", "--format=%H%x1f%s%x1f%b%x1e", "--", path)
    commits = []
    for record in raw.split("\x1e"):
        if not record.strip():
            continue
        parts = record.strip().split("\x1f")
        if len(parts) != 3:
            continue
        commit_hash, subject, body = parts
        message = f"{subject}\n{body}".strip()
        has_human_signal = bool(HUMAN_SIGNAL_RE.search(message))
        is_ai_generated = bool(AI_GENERATED_RE.search(message))
        commits.append(
            {
                "hash": commit_hash,
                "message": message,
                "has_human_signal": has_human_signal,
                "is_ai_generated": is_ai_generated,
            }
        )
    return commits


def blame_line_counts(path: str) -> dict[str, int]:
    raw = run_git("blame", "--line-porcelain", path)
    counts: dict[str, int] = {}
    for line in raw.splitlines():
        if re.match(r"^[0-9a-f]{40} \d+ \d+( \d+)?$", line):
            parts = line.split()
            commit_hash = parts[0]
            line_count = int(parts[3]) if len(parts) > 3 else 1
            counts[commit_hash] = counts.get(commit_hash, 0) + line_count
    return counts

results = {}
for name, path in PAGES.items():
    commits = load_commits(path)
    total = len(commits)
    blame_counts = blame_line_counts(path) if total else {}
    total_lines = sum(blame_counts.values())

    # Check each commit for co-authorship
    ai_count = 0
    for commit in commits:
        body = run_git("log", "-1", "--format=%b", commit["hash"])
        if "Co-Authored-By" in body and "Claude" in body:
            ai_count += 1

    human_edit_commits = [
        commit
        for commit in commits
        if commit["has_human_signal"] and not commit["is_ai_generated"]
    ]
    human_edit_hashes = {commit["hash"] for commit in human_edit_commits}
    human_edit_lines = sum(blame_counts.get(commit_hash, 0) for commit_hash in human_edit_hashes)
    human_edit_ratio = (human_edit_lines / total_lines) if total_lines else 0.0
    latest_is_human_edit = bool(
        commits and commits[0]["hash"] in human_edit_hashes
    )
    has_reliable_human_edits = bool(human_edit_commits) and total >= 2
    effectively_human_written = (
        total >= 2
        and human_edit_lines >= 20
        and human_edit_ratio >= 0.6
        and (latest_is_human_edit or len(human_edit_commits) >= 2)
    )
    human_directed = name in HUMAN_DIRECTED

    if total == 0:
        badge = "unknown"
        color = "grey"
    elif effectively_human_written:
        badge = "Effectively human-written"
        color = "green"
    elif human_directed:
        badge = "AI-drafted, human-directed"
        color = "yellow"
    elif has_reliable_human_edits:
        badge = "AI-drafted, human-edited"
        color = "yellow"
    else:
        badge = "AI-drafted"
        color = "red"

    results[name] = {
        "badge": badge,
        "color": color,
        "total_commits": total,
        "ai_commits": ai_count,
        "human_edits": len(human_edit_commits),
        "human_edit_lines": human_edit_lines,
        "human_edit_ratio": round(human_edit_ratio, 3),
        "github_url": f"{GITHUB_BASE}/commits/main/{path}",
    }

# Output as JSON
print(json.dumps(results, indent=2))
